import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../Header';
import Home from '../home';
import ScrollVelocity from '@/TextAnimations/ScrollVelocity/ScrollVelocity';
import HeroSlider from '../components/HeroSlider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <HeroSlider />
        <ScrollVelocity
          texts={['Welcome to', 'Demo Store']}
          className="scroll-text"
          velocity={40} // Slower speed
          damping={40} // More damping
          stiffness={150} // Softer spring
          velocityMapping={{ input: [0, 400], output: [0, 2.5] }} 
        />
      </body>
    </html>
  )
}